
// This file was auto-generated by ML.NET Model Builder. 

using ShipModel_V3_0;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\nickl\OneDrive\Desktop\Ships Dataset Sorted\Aircraft Carrier\ARA-Veinticinco-de-Mayo-V2_jpg.rf.4619f212949ef813605a432b97e20326.jpg");
TestModel.ModelInput sampleData = new TestModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = TestModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");
